version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./closset.db
      - SECRET_KEY=your-secret-key-here
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend/web-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/web-app:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"